// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/aclevername/config-map-controller/controller"
	v1 "k8s.io/api/core/v1"
)

type FakeProcessor struct {
	ProcessResourceStub        func(*v1.ConfigMap) error
	processResourceMutex       sync.RWMutex
	processResourceArgsForCall []struct {
		arg1 *v1.ConfigMap
	}
	processResourceReturns struct {
		result1 error
	}
	processResourceReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProcessor) ProcessResource(arg1 *v1.ConfigMap) error {
	fake.processResourceMutex.Lock()
	ret, specificReturn := fake.processResourceReturnsOnCall[len(fake.processResourceArgsForCall)]
	fake.processResourceArgsForCall = append(fake.processResourceArgsForCall, struct {
		arg1 *v1.ConfigMap
	}{arg1})
	fake.recordInvocation("ProcessResource", []interface{}{arg1})
	fake.processResourceMutex.Unlock()
	if fake.ProcessResourceStub != nil {
		return fake.ProcessResourceStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.processResourceReturns
	return fakeReturns.result1
}

func (fake *FakeProcessor) ProcessResourceCallCount() int {
	fake.processResourceMutex.RLock()
	defer fake.processResourceMutex.RUnlock()
	return len(fake.processResourceArgsForCall)
}

func (fake *FakeProcessor) ProcessResourceCalls(stub func(*v1.ConfigMap) error) {
	fake.processResourceMutex.Lock()
	defer fake.processResourceMutex.Unlock()
	fake.ProcessResourceStub = stub
}

func (fake *FakeProcessor) ProcessResourceArgsForCall(i int) *v1.ConfigMap {
	fake.processResourceMutex.RLock()
	defer fake.processResourceMutex.RUnlock()
	argsForCall := fake.processResourceArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeProcessor) ProcessResourceReturns(result1 error) {
	fake.processResourceMutex.Lock()
	defer fake.processResourceMutex.Unlock()
	fake.ProcessResourceStub = nil
	fake.processResourceReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessor) ProcessResourceReturnsOnCall(i int, result1 error) {
	fake.processResourceMutex.Lock()
	defer fake.processResourceMutex.Unlock()
	fake.ProcessResourceStub = nil
	if fake.processResourceReturnsOnCall == nil {
		fake.processResourceReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.processResourceReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProcessor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.processResourceMutex.RLock()
	defer fake.processResourceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProcessor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ controller.Processor = new(FakeProcessor)
